backend:
  name: git-gateway
  branch: main # Replace with your default branch

media_folder: "assets/images/uploads" # Folder where images are stored
public_folder: "/assets/images/uploads" # Public path to the images

collections:
  - name: "projects" # Name of the collection
    label: "Projects"
    folder: "content/projects" # Folder where project markdown files are stored
    create: true # Allow users to create new projects
    slug: "{{slug}}" # File name format
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }